/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.haley.lista02;
import java.security.PublicKey;
import java.util.ArrayList;
/**
 *
 * @author haley
 */
public class Exec05Imc extends javax.swing.JFrame {

    /**
     * Creates new form Exec05Imc
     */
    public Exec05Imc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        txtFldPeso = new javax.swing.JTextField();
        txtFldAltura = new javax.swing.JTextField();
        rdBtnMasculino = new javax.swing.JRadioButton();
        rdBtnFeminino = new javax.swing.JRadioButton();
        btnCalculo = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("IMC");

        lblPeso.setText("Peso:");

        lblAltura.setText("Altura:");

        rdBtnMasculino.setText("Masculino");

        rdBtnFeminino.setText("Feminino");
        rdBtnFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnFemininoActionPerformed(evt);
            }
        });

        btnCalculo.setText("Calcular imc");
        btnCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(txtFldPeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAltura)
                    .addComponent(txtFldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(rdBtnMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdBtnFeminino))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCalculo))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(lblAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnMasculino)
                    .addComponent(rdBtnFeminino))
                .addGap(18, 18, 18)
                .addComponent(btnCalculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtnFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnFemininoActionPerformed

    private void btnCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoActionPerformed
        // TODO add your handling code here:
        Double altura = Double.valueOf(txtFldAltura.getText());
        Double peso = Double.valueOf(txtFldPeso.getText());
        
        Double imc = peso / Math.pow(altura,2);
        
//        ArrayList<Integer> nmrButton = new ArrayList<Integer>();
        Integer sexo = 0;


        if(rdBtnMasculino.isSelected()) {
            sexo = 1;
        }
        
        if(rdBtnFeminino.isSelected()) {
            sexo = 2;
        }        
        
        switch (sexo) {
            case 1 :
                mascImc(imc);
                break;
            case 2 :
                femiImc(imc);
                break;     
        }
    }//GEN-LAST:event_btnCalculoActionPerformed
    
    private void mascImc(Double imcPessoa) {
        if(imcPessoa < 20.7) {
            lblResultado.setText("abaixo do peso");
        }    
        if(imcPessoa >= 20.7 && imcPessoa < 26.4) {
            lblResultado.setText("no peso normal");
        }    
        if(imcPessoa >= 26.4 && imcPessoa < 27.8) {
            lblResultado.setText("marginalmente acima do peso");
        }    
        if(imcPessoa >= 27.8 && imcPessoa < 31.1) {
            lblResultado.setText("acima do peso ideal");
        }    
        if(imcPessoa > 31.1) {
            lblResultado.setText("obeso");
        }    
    }
    private void femiImc(Double imcPessoa) {
        if(imcPessoa < 19.1) {
            lblResultado.setText("abaixo do peso");
        }    
        if(imcPessoa >= 19.1 && imcPessoa < 25.8) {
            lblResultado.setText("no peso normal");
        }    
        if(imcPessoa >= 25.8 && imcPessoa < 27.3) {
            lblResultado.setText("marginalmente acima do peso");
        }    
        if(imcPessoa >= 27.3 && imcPessoa < 32.3) {
            lblResultado.setText("acima do peso ideal");
        }    
        if(imcPessoa > 32.3) {
            lblResultado.setText("obeso");
        }    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exec05Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exec05Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exec05Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exec05Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exec05Imc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculo;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rdBtnFeminino;
    private javax.swing.JRadioButton rdBtnMasculino;
    private javax.swing.JTextField txtFldAltura;
    private javax.swing.JTextField txtFldPeso;
    // End of variables declaration//GEN-END:variables
}
